language: python
python: 
    - "2.7"

# install dependencies
install:
    - sudo python setup.py install

# run the tests
script: 
    - sudo python setup.py flake8
    - sudo python setup.py nosetests
