language: python
python: 
    - "2.7"

# install dependencies
install:
    - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list 
    - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    - sudo apt-get update -q
    - sudo apt-get install rethinkdb --force-yes
    - sudo python setup.py install

# run the tests
script: 
    - sudo rethinkdb --daemon
    - sudo python setup.py flake8
    - sudo python setup.py nosetests
